#!/usr/bin/env bash

set -e

vol_cmd() {
  amixer sget Master | grep 'Right:' | awk -F"[][]" '{ print $2 }'
}

ip_cmd() {
  hostname -I
}

batt_cmd() {
  upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{ print $2 }'
}

weather() {
  cat /tmp/weather
}

while xsetroot -name " weather: $(weather) | vol: $(vol_cmd) | ip: $(ip_cmd) | batt: $(batt_cmd) | $(date)"
do
  sleep 1
done
