#!/usr/bin/env bash

set -e

vol_cmd() {
  amixer sget Master | grep 'Right:' | awk -F"[][]" '{ print $2 }'
}

ip_cmd() {
  ip addr show dev wlp58s0 | grep 'inet ' | awk '{ print $2 }'
}

batt_cmd() {
  upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{ print $2 }'
}

while xsetroot -name " vol: $(vol_cmd) | $(ip_cmd) | batt: $(batt_cmd) | $(date)"
do
  sleep 1
done
